/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.espoch.principal;

import edu.espoch.arbol.modelo.CArbol;
import edu.espoch.estado.modelo.CEstado;
import java.util.List;

/**
 *
 * @author root
 */
public class jfrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jfrmPrincipal
     */
    public jfrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMrg = new javax.swing.JTextField();
        txtMrp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCantidadDeseada = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnSolucion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel1.setText("Problema de los recipientes de agua");

        jLabel2.setText("Máximo Recipiente Grande:");

        jLabel3.setText("Máximo Recipiente Pequeño:");

        txtMrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMrgActionPerformed(evt);
            }
        });

        txtMrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMrpActionPerformed(evt);
            }
        });

        jLabel4.setText("Cantidad a buscar:");

        jLabel5.setText("Solución:");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnSolucion.setText("Solución");
        btnSolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolucionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMrp, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txtMrg, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCantidadDeseada, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(btnSolucion))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(171, 171, 171))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCantidadDeseada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSolucion))
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMrgActionPerformed

    private void txtMrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMrpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMrpActionPerformed

    private void btnSolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolucionActionPerformed

        Integer mrg = Integer.parseInt(txtMrg.getText());
        Integer mrp = Integer.parseInt(txtMrp.getText());
        Integer cd = Integer.parseInt(txtCantidadDeseada.getText());
        CArbol arbol = new CArbol(mrg, mrp, cd);
        arbol.crearArbol();

        List<CEstado> lstSol = arbol.solucion();
        //jTextArea1.setText("Raiz: ( " + arbol.getRaiz().getInformacionNodoArbol().getRecipienteGrande() + "," + arbol.getRaiz().getInformacionNodoArbol().getRecipientePequenio() + " )");
        //jTextArea1.append(System.getProperty("line.separator")); salto de linea
        jTextArea1.append("Primera solución encontrada.");
        jTextArea1.append(System.getProperty("line.separator"));
        if (lstSol != null) {
            for (CEstado lstSol1 : lstSol) {
                jTextArea1.append("(" + lstSol1.getRecipienteGrande() + "," + lstSol1.getRecipientePequenio() + ") - ");
            }
        }
        jTextArea1.append(System.getProperty("line.separator"));
        jTextArea1.append("Mejor solución encontrada.");
        jTextArea1.append(System.getProperty("line.separator"));
        recorrerMejorSolucion(arbol.mejorSolucion());
        
        jTextArea1.append(System.getProperty("line.separator"));
        jTextArea1.append("Todas la soluciones.");
        jTextArea1.append(System.getProperty("line.separator"));
        recorrerTodosSolucion(arbol.listarTodasSoluciones());

    }//GEN-LAST:event_btnSolucionActionPerformed

    private void recorrerMejorSolucion(List<CEstado> lstSol) {
        CEstado aux = null;
        if (lstSol != null) {
            for (CEstado lstSol1 : lstSol) {
                aux = lstSol1;
                jTextArea1.append("(" + lstSol1.getRecipienteGrande() + "," + lstSol1.getRecipientePequenio() + ") - ");
            }
        }
    }

    private void recorrerTodosSolucion(List<List<CEstado>> lstSoluciones) {
        CEstado aux = null;
        if (lstSoluciones != null) {
            for (int i = 0; i < lstSoluciones.size(); i++) {
                jTextArea1.append(System.getProperty("line.separator"));
                for (int j = 0; j < lstSoluciones.get(i).size(); j++) {
                    aux = lstSoluciones.get(i).get(j);
                    jTextArea1.append("(" + aux.getRecipienteGrande() + "," + aux.getRecipientePequenio() + ") - ");
                }
                jTextArea1.append(System.getProperty("line.separator"));
                jTextArea1.append("________________________________________________________________________");
                
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSolucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtCantidadDeseada;
    private javax.swing.JTextField txtMrg;
    private javax.swing.JTextField txtMrp;
    // End of variables declaration//GEN-END:variables
}
